_BASE_: "Base-C2_L_R5021k_640b64_4x.yaml"
MODEL:
  MASK_ON: False
  ROI_HEADS:
    NUM_CLASSES: 466
  CENTERNET:
    NUM_CLASSES: 466
  ROI_BOX_HEAD:
    USE_ZEROSHOT_CLS: True
    IMAGE_LABEL_LOSS: 'max_size'
    USE_SIGMOID_CE: True
    ZEROSHOT_WEIGHT_PATH: 'datasets/metadata/ovd360_clip.npy'
    IGNORE_ZERO_CATS: True
    CAT_FREQ_PATH: 'datasets/metadata/ovd360_cat_info.json'
    USE_FED_LOSS: False      # do not use fed
  WEIGHTS: "models/Detic_LbaseI_CLIP_SwinB_896b32_4x_ft4x_max-size.pth"
  BACKBONE:
    NAME: build_swintransformer_fpn_backbone
  SWIN:
    SIZE: B-22k
  FPN:
    IN_FEATURES: ["swin1", "swin2", "swin3"]

SOLVER:
  MAX_ITER: 90000
  IMS_PER_BATCH: 64
  BASE_LR: 0.0002
  WARMUP_ITERS: 1000
  WARMUP_FACTOR: 0.001
  CHECKPOINT_PERIOD: 1000000000
TEST:
  DETECTIONS_PER_IMAGE: 100
  EVAL_PERIOD: 90000
DATASETS:
  TRAIN: ("ovd360_train","ovd365_images")
  TEST: ("ovd360_test",)
DATALOADER:
  SAMPLER_TRAIN: "MultiDatasetSampler"
  DATASET_RATIO: [1, 4]
  USE_DIFF_BS_SIZE: True
  DATASET_BS: [8, 32]
  DATASET_INPUT_SIZE: [896, 448]
  USE_RFS: [False, False]     # do not use rfs
  DATASET_INPUT_SCALE: [[0.1, 2.0], [0.5, 1.5]]
  FILTER_EMPTY_ANNOTATIONS: False
  MULTI_DATASET_GROUPING: True
  DATASET_ANN: ['box', 'image']
  NUM_WORKERS: 8
WITH_IMAGE_LABELS: True